name: installed_apps
description: Flutter plugin with utility methods related to installed apps on device.
version: 1.1.1
homepage: https://github.com/sharmadhiraj/installed_apps

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.sharmadhiraj.installed_apps
    pluginClass: InstalledAppsPlugin